<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/assistant/embedded/v1alpha2/embedded_assistant.proto

namespace Google\Assistant\Embedded\V1alpha2\DialogStateOut;

use UnexpectedValueException;

/**
 * Possible states of the microphone after a `Assist` RPC completes.
 *
 * Protobuf type <code>google.assistant.embedded.v1alpha2.DialogStateOut.MicrophoneMode</code>
 */
class MicrophoneMode
{
    /**
     * No mode specified.
     *
     * Generated from protobuf enum <code>MICROPHONE_MODE_UNSPECIFIED = 0;</code>
     */
    const MICROPHONE_MODE_UNSPECIFIED = 0;
    /**
     * The service is not expecting a follow-on question from the user.
     * The microphone should remain off until the user re-activates it.
     *
     * Generated from protobuf enum <code>CLOSE_MICROPHONE = 1;</code>
     */
    const CLOSE_MICROPHONE = 1;
    /**
     * The service is expecting a follow-on question from the user. The
     * microphone should be re-opened when the `AudioOut` playback completes
     * (by starting a new `Assist` RPC call to send the new audio).
     *
     * Generated from protobuf enum <code>DIALOG_FOLLOW_ON = 2;</code>
     */
    const DIALOG_FOLLOW_ON = 2;

    private static $valueToName = [
        self::MICROPHONE_MODE_UNSPECIFIED => 'MICROPHONE_MODE_UNSPECIFIED',
        self::CLOSE_MICROPHONE => 'CLOSE_MICROPHONE',
        self::DIALOG_FOLLOW_ON => 'DIALOG_FOLLOW_ON',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(MicrophoneMode::class, \Google\Assistant\Embedded\V1alpha2\DialogStateOut_MicrophoneMode::class);

